"""
Run the full AIRMM swaption pricing and sensitivity pipeline.

This script is the main project wrapper.

It reproduces the core VBA workflow:

1. VOL_LONG_ALL
2. CASH_IRR_FWD_PREM_LONG
3. SENS_LONG_005
4. SENS_FD_CHECK_005

Usage
-----
From the project root:

    python scripts/run_full_pipeline.py

Optional:

    python scripts/run_full_pipeline.py \
        --market-workbook AIRMM-MarketData31Oct2019.xlsx \
        --basics-workbook AIRMM-Exercises-Basics.xlsm \
        --output-dir outputs
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


from src.cash_irr import build_cash_irr_forward_premia, cash_irr_summary
from src.config import DEFAULT_SHIFT
from src.market_data import (
    DEFAULT_BASICS_WORKBOOK_NAME,
    DEFAULT_MARKET_WORKBOOK_NAME,
    load_airmm_workbook,
    workbook_summary,
)
from src.sensitivities import (
    build_sens_fd_check_005,
    build_sens_long_005,
    sensitivities_summary,
)
from src.vol_cube import build_vol_long_all, volatility_cube_summary


@dataclass(frozen=True)
class PipelineResult:
    """
    Output tables generated by the full pipeline.
    """

    vol_long: pd.DataFrame
    cash_irr: pd.DataFrame
    sens_long_005: pd.DataFrame
    sens_fd_check_005: pd.DataFrame


def _write_csv(df: pd.DataFrame, path: Path) -> None:
    """
    Write a dataframe to CSV using stable project settings.
    """
    df.to_csv(path, index=False)


def run_full_pipeline(
    market_workbook: str | Path = DEFAULT_MARKET_WORKBOOK_NAME,
    basics_workbook: str | Path = DEFAULT_BASICS_WORKBOOK_NAME,
    output_dir: str | Path = "outputs",
) -> PipelineResult:
    """
    Run the full pricing and sensitivity pipeline.

    Parameters
    ----------
    market_workbook:
        Workbook containing market data and yield curves.
    basics_workbook:
        Workbook containing shared calendar data.
    output_dir:
        Directory where generated CSV outputs are written.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    print("Loading AIRMM workbooks...")

    market_data = load_airmm_workbook(
        market_file_path=market_workbook,
        basics_file_path=basics_workbook,
    )

    print("Workbook summary:")
    for key, value in workbook_summary(market_data).items():
        print(f"  {key}: {value}")

    print("\nBuilding VOL_LONG_ALL...")
    vol_long = build_vol_long_all(market_data)
    vol_summary = volatility_cube_summary(vol_long)

    _write_csv(vol_long, output_path / "vol_long_all.csv")
    _write_csv(vol_summary, output_path / "vol_long_summary.csv")

    print(f"  VOL_LONG_ALL shape: {vol_long.shape}")

    print("\nBuilding CASH_IRR_FWD_PREM_LONG...")
    cash_irr = build_cash_irr_forward_premia(
        vol_long=vol_long,
        holidays=market_data.holidays,
    )
    cash_summary = cash_irr_summary(cash_irr)

    _write_csv(cash_irr, output_path / "cash_irr_fwd_prem_long.csv")
    _write_csv(cash_summary, output_path / "cash_irr_summary.csv")

    print(f"  CASH_IRR_FWD_PREM_LONG shape: {cash_irr.shape}")

    print(f"\nBuilding SENS_LONG_{int(DEFAULT_SHIFT * 1000):03d}...")
    sens_long_005 = build_sens_long_005(
        vol_long=vol_long,
        curve=market_data.ois_curve,
        holidays=market_data.holidays,
        target_shift=DEFAULT_SHIFT,
    )

    print(f"  SENS_LONG_005 shape: {sens_long_005.shape}")

    print("\nBuilding SENS_FD_CHECK_005...")
    sens_fd_check_005 = build_sens_fd_check_005(
        vol_long=vol_long,
        curve=market_data.ois_curve,
        holidays=market_data.holidays,
        target_shift=DEFAULT_SHIFT,
    )

    print(f"  SENS_FD_CHECK_005 shape: {sens_fd_check_005.shape}")

    _write_csv(sens_long_005, output_path / "sens_long_005.csv")
    _write_csv(sens_fd_check_005, output_path / "sens_fd_check_005.csv")

    sens_summary = sensitivities_summary(
        sens_long=sens_long_005,
        sens_fd_check=sens_fd_check_005,
    )

    summary_rows = [
        {
            "Table": "VOL_LONG_ALL",
            "Rows": vol_long.shape[0],
            "Columns": vol_long.shape[1],
        },
        {
            "Table": "CASH_IRR_FWD_PREM_LONG",
            "Rows": cash_irr.shape[0],
            "Columns": cash_irr.shape[1],
        },
        {
            "Table": "SENS_LONG_005",
            "Rows": sens_long_005.shape[0],
            "Columns": sens_long_005.shape[1],
        },
        {
            "Table": "SENS_FD_CHECK_005",
            "Rows": sens_fd_check_005.shape[0],
            "Columns": sens_fd_check_005.shape[1],
        },
        {
            "Table": "SENS_LONG_005_VALID_ROWS",
            "Rows": sens_summary["sens_long_valid_rows"],
            "Columns": None,
        },
        {
            "Table": "SENS_LONG_005_BLANK_ROWS",
            "Rows": sens_summary["sens_long_blank_rows"],
            "Columns": None,
        },
    ]

    pipeline_summary = pd.DataFrame(summary_rows)
    _write_csv(pipeline_summary, output_path / "pipeline_summary.csv")

    print("\nPipeline summary:")
    print(pipeline_summary.to_string(index=False))

    print("\nGenerated files:")
    generated_files = [
        "vol_long_all.csv",
        "vol_long_summary.csv",
        "cash_irr_fwd_prem_long.csv",
        "cash_irr_summary.csv",
        "sens_long_005.csv",
        "sens_fd_check_005.csv",
        "pipeline_summary.csv",
    ]

    for filename in generated_files:
        print(f"  {output_path / filename}")

    return PipelineResult(
        vol_long=vol_long,
        cash_irr=cash_irr,
        sens_long_005=sens_long_005,
        sens_fd_check_005=sens_fd_check_005,
    )


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="Run the full AIRMM swaption pricing and sensitivity pipeline.",
    )

    parser.add_argument(
        "--market-workbook",
        default=DEFAULT_MARKET_WORKBOOK_NAME,
        help="Path to AIRMM-MarketData31Oct2019.xlsx.",
    )

    parser.add_argument(
        "--basics-workbook",
        default=DEFAULT_BASICS_WORKBOOK_NAME,
        help="Path to AIRMM-Exercises-Basics.xlsm.",
    )

    parser.add_argument(
        "--output-dir",
        default="outputs",
        help="Directory where CSV outputs are written.",
    )

    return parser.parse_args()


def main() -> None:
    """
    Command-line entry point.
    """
    args = parse_args()

    run_full_pipeline(
        market_workbook=args.market_workbook,
        basics_workbook=args.basics_workbook,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    main()